In [225]:
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline

def gaussian_elimination(Ab, row, column): 
    for i in range(0, column-1):
        for j in range(i+1, row+1):
            Ab[j,:] = Ab[j,:] - Ab[j,i]*(Ab[i,:]/Ab[i,i])
    return(Ab) 

def back_subsitution(Ab, row, column): 

    count = 0 

    for j in range(column, 0, -1): 
        Ab[row-count,:] = Ab[row-count,:]/Ab[row-count, column-count-1]
        var = Ab[row-count, column]/Ab[row-count, column-count-1]
        for i in range((-count - 1) % (row+1), 0, -1):
            Ab[i-1, column:] = Ab[i-1, column:]-(Ab[i-1,j-1]*var)
            Ab[i-1, j-1] = 0
        count += 1 
    return(Ab)

def row_length(Ab): 
    return len(Ab)-1

def column_length(Ab):
    return len(Ab[0])-1


In [222]:
np.set_printoptions(formatter={'float':'{: 0.1f}'.format})

A = np.array([[ 2.,-4., 1., 2., -3.], [ 1., 4.,-2.,-1., 1.], [-3., 1.,-2., 5.,-3.], [-5., 3.,-3., 5.,-1.],[-4.,-2., 1., 1.,-2.] ])
b = np.array([[-12., 7., -4., 6., -17.]])
Ab = np.concatenate((A, b.T), axis=1)


In [223]:
row = row_length(Ab)
column = column_length(Ab)

Ab = gaussian_elimination(Ab, row, column)
Ab = back_subsitution(Ab, row, column)

print(Ab)


[[ 1.0  0.0  0.0  0.0  0.0  2.0]
 [ 0.0  1.0  0.0  0.0  0.0  3.0]
 [-0.0 -0.0  1.0 -0.0 -0.0  4.0]
 [-0.0 -0.0 -0.0  1.0 -0.0  5.0]
 [-0.0 -0.0 -0.0 -0.0  1.0  6.0]]


In [227]:
#i know this gives an error, because of the count variable in my back subsitution function but I can't figure out how to fix it
#here are some whimiscal unicode figures if you wish to pay attention to these instead: 😇 🚰 🎟 🐺 🐎 🐽 🍱

i = np.identity(5)
Ai = np.concatenate((A, i), axis=1)

row = row_length(Ai)
column = column_length(Ai)

Ai = gaussian_elimination(Ai, row, column)
Ai = back_subsitution(Ai, row, column)

print(Ai)


[[ 0.0  0.0  0.0  0.0  1.0 -0.0 -0.0 -0.0 -0.0  nan]
 [ nan  nan  nan  nan  inf -inf  nan  nan  nan  nan]
 [ nan  nan  nan  nan -inf  inf  inf  nan  nan  nan]
 [ nan  nan  nan  nan  inf  inf  inf -inf  nan  nan]
 [ nan  nan  nan  nan -inf -inf  inf  inf -inf  inf]]


C:\Users\Christa\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:17: RuntimeWarning: divide by zero encountered in double_scalars
C:\Users\Christa\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:19: RuntimeWarning: invalid value encountered in double_scalars
C:\Users\Christa\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:16: RuntimeWarning: divide by zero encountered in true_divide
C:\Users\Christa\Anaconda3\lib\site-packages\IPython\kernel\__main__.py:16: RuntimeWarning: invalid value encountered in true_divide
